20-Dec-2024 00:04:30.711 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:04:30.712 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:04:35.097 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:04:35.098 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:04:35.099 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@39c96e48')
20-Dec-2024 00:04:56.237 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:04:56.237 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:04:59.776 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:04:59.776 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:04:59.778 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@47768e74')
20-Dec-2024 00:05:34.312 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:05:34.312 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:05:37.775 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:05:37.775 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:05:37.776 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@76130a29')
20-Dec-2024 00:08:51.818 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:08:51.818 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:08:57.316 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:08:57.316 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:08:57.318 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@5fef2aac')
20-Dec-2024 00:15:00.897 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:15:00.897 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:15:04.818 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:15:04.818 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:15:04.820 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@76130a29')
20-Dec-2024 00:17:33.234 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:17:33.234 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:17:37.704 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:17:37.704 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:17:37.705 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@16a5eb6d')
20-Dec-2024 00:17:53.795 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:17:53.795 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:17:58.115 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:17:58.115 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:17:58.117 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@76130a29')
20-Dec-2024 00:24:22.748 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:24:22.748 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:24:26.235 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:24:26.235 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:24:26.237 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@668625f5')
20-Dec-2024 00:25:18.258 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:25:18.258 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:31:38.529 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:31:38.530 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:31:38.531 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@5fef2aac')
20-Dec-2024 00:32:36.642 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLException: PrepareStatement.executeQuery() command does NOT return a result-set as expected. Either use PrepareStatement.execute(), PrepareStatement.executeUpdate(), or correct command
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:54)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLException: PrepareStatement.executeQuery() command does NOT return a result-set as expected. Either use PrepareStatement.execute(), PrepareStatement.executeUpdate(), or correct command
		at org.mariadb.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:279)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:49)
		... 22 more
20-Dec-2024 00:33:03.430 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:33:03.430 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:36:48.217 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:36:48.217 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:36:48.219 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@76130a29')
20-Dec-2024 00:37:21.452 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:54)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:49)
		... 22 more
20-Dec-2024 00:37:23.637 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:54)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:49)
		... 22 more
20-Dec-2024 00:37:24.277 SEVERE [http-nio-8080-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:54)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:49)
		... 22 more
20-Dec-2024 00:37:24.720 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:54)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:49)
		... 22 more
20-Dec-2024 00:42:17.345 SEVERE [http-nio-8080-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:54)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:49)
		... 22 more
20-Dec-2024 00:42:18.119 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:54)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=247) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:49)
		... 22 more
20-Dec-2024 00:42:59.450 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:42:59.450 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 00:43:07.152 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 00:43:07.152 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 00:43:07.154 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@76130a29')
20-Dec-2024 00:48:01.992 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:57)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 00:48:06.265 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:57)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 00:48:06.867 SEVERE [http-nio-8080-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:57)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 00:48:07.128 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:57)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 00:48:07.329 SEVERE [http-nio-8080-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:57)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 00:48:07.555 SEVERE [http-nio-8080-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:57)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=249) Duplicate entry '0' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 00:56:11.113 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 00:56:11.113 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 01:12:17.285 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 01:12:17.285 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 01:12:17.286 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@1a565afb')
20-Dec-2024 01:12:44.865 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:12:51.495 SEVERE [http-nio-8080-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:12:52.132 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:12:52.699 SEVERE [http-nio-8080-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:12:52.936 SEVERE [http-nio-8080-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:12:53.127 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:12:53.280 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:13:17.150 SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:13:17.397 SEVERE [http-nio-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:13:17.588 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:13:17.748 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:13:18.053 SEVERE [http-nio-8080-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:13:18.256 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCategory] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:58)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=251) Duplicate entry '4' for key 'PRIMARY'
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:323)
		at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:300)
		at Onlineshopping.Admin.AddCategory.doGet(AddCategory.java:52)
		... 22 more
20-Dec-2024 01:14:27.787 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 01:14:27.787 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 01:14:30.804 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 01:14:30.804 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 01:14:30.806 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@590f0c50')
20-Dec-2024 01:15:20.517 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 01:15:20.517 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 11:58:42.396 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 11:58:42.396 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 11:58:42.398 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@40d23c82')
20-Dec-2024 12:03:25.623 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 12:03:25.623 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 12:03:29.880 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 12:03:29.881 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 12:03:29.882 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@124d02b2')
20-Dec-2024 12:03:56.553 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 12:03:56.554 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 12:04:21.809 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 12:04:21.810 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 12:04:21.812 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@3a90c13c')
20-Dec-2024 12:04:59.327 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [Onlineshopping.Admin.DeleteCategory] threw exception
	java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.executeUpdate(String)" because "this.psDeleteStatement" is null
		at Onlineshopping.Admin.DeleteCategory.init(DeleteCategory.java:28)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:817)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:787)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:568)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
20-Dec-2024 12:04:59.327 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [Onlineshopping.Admin.DeleteCategory]
	java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.executeUpdate(String)" because "this.psDeleteStatement" is null
		at Onlineshopping.Admin.DeleteCategory.init(DeleteCategory.java:28)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:817)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:787)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:568)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
20-Dec-2024 12:05:25.370 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 12:05:25.370 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 12:07:11.909 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 12:07:11.909 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 12:07:11.910 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@6587305a')
20-Dec-2024 12:10:13.765 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 12:10:13.765 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 15:27:14.061 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 15:27:14.061 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 15:27:14.063 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@124d02b2')
20-Dec-2024 15:37:02.980 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 15:37:02.980 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 15:37:06.838 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 15:37:06.838 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 15:37:06.840 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@655f69da')
20-Dec-2024 15:40:09.370 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 15:40:09.370 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 15:40:12.534 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 15:40:12.534 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 15:40:12.536 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@5befbac1')
20-Dec-2024 15:43:30.274 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 15:43:30.274 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 15:43:33.425 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 15:43:33.425 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 15:43:33.427 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@7cf78c85')
20-Dec-2024 15:48:56.613 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 15:48:56.613 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 16:01:54.759 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 16:01:54.759 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 16:01:54.761 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@76130a29')
20-Dec-2024 16:07:11.293 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 16:07:11.294 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 16:13:48.571 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 16:13:48.573 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 16:13:48.575 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@3451f01d')
20-Dec-2024 16:20:57.807 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 16:20:57.808 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 17:05:58.344 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 17:05:58.344 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 17:05:58.346 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@3451f01d')
20-Dec-2024 17:06:18.136 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 17:06:18.136 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 17:07:16.704 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 17:07:16.704 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 17:07:16.706 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@655f69da')
20-Dec-2024 17:07:19.178 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 17:07:19.178 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 18:21:26.462 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 18:21:26.463 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 18:21:26.465 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@6aa7b67f')
20-Dec-2024 18:21:43.416 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 18:21:43.416 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 18:22:17.245 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 18:22:17.245 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 18:22:17.247 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@3451f01d')
20-Dec-2024 18:24:34.466 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 18:24:34.466 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 18:24:37.412 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 18:24:37.412 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 18:24:37.413 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@66deec87')
20-Dec-2024 18:26:02.978 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCard] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: (conn=277) Incorrect date value: '31/12/2025' for column `onlineshopping`.`CardDetails`.`ExpirationDate` at row 1
		at Onlineshopping.Admin.AddCard.doPost(AddCard.java:48)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:645)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLSyntaxErrorException: (conn=277) Incorrect date value: '31/12/2025' for column `onlineshopping`.`CardDetails`.`ExpirationDate` at row 1
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:289)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:247)
		at Onlineshopping.Admin.AddCard.doPost(AddCard.java:43)
		... 22 more
20-Dec-2024 18:26:22.431 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 18:26:22.431 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 18:26:34.463 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 18:26:34.463 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 18:26:34.465 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@124d02b2')
20-Dec-2024 18:29:32.278 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Onlineshopping.Admin.AddCard] in context with path [/OnlineShopping] threw exception
	java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: (conn=279) Incorrect date value: '31-12-2025' for column `onlineshopping`.`CardDetails`.`ExpirationDate` at row 1
		at Onlineshopping.Admin.AddCard.doPost(AddCard.java:48)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:645)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLSyntaxErrorException: (conn=279) Incorrect date value: '31-12-2025' for column `onlineshopping`.`CardDetails`.`ExpirationDate` at row 1
		at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:289)
		at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
		at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189)
		at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1246)
		at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1185)
		at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1104)
		at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1028)
		at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:101)
		at org.mariadb.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:247)
		at Onlineshopping.Admin.AddCard.doPost(AddCard.java:43)
		... 22 more
20-Dec-2024 18:40:22.075 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 18:40:22.075 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 18:40:24.895 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 18:40:24.896 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 18:40:24.897 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@6bcc3f27')
20-Dec-2024 18:41:22.622 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 18:41:22.622 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 22:10:46.039 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 22:10:46.039 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 22:10:46.041 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@688a2c09')
20-Dec-2024 22:12:19.205 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 22:12:19.206 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 22:17:07.381 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 22:17:07.381 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 22:17:07.382 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@124d02b2')
20-Dec-2024 22:18:32.301 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 22:18:32.301 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 22:18:35.372 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 22:18:35.372 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 22:18:35.374 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@72503b19')
20-Dec-2024 22:19:15.996 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 22:19:15.996 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 22:19:21.555 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 22:19:21.555 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 22:19:21.557 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@ebe067d')
20-Dec-2024 22:26:27.397 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 22:26:27.397 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
20-Dec-2024 22:49:04.329 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
20-Dec-2024 22:49:04.329 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
20-Dec-2024 22:49:04.331 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@314b9e4b')
20-Dec-2024 22:52:43.572 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
20-Dec-2024 22:52:43.572 INFO [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
